In [1]:
%load_ext Cython

In [5]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
cimport cython
from cython.view cimport array as cvarray
import numpy as np
cimport numpy as np
np.import_array()


cdef double[:]f(int n):
    cdef double[:] x = cvarray(shape=(n,), itemsize=sizeof(double), format="d")
    cdef int i
    for i in range(n):
        x[i] = i
    return x

print(f(10))


<MemoryView of 'array' object>


In [74]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION

cimport numpy as cnp
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np
cimport cython
cnp.import_array()

data = ["2022-01-01", "2022-01-01"]

# cdef dtarray(x):
#     # a = cnp.PyArra
#     cdef cnp.ndarray a 
#     a = np.asanyarray(x, dtype="datetime64[ns]").ravel() # type: ignore
#     # cdef cnp.ndarray dt
#     return cnp.PyArray_Cast(a, cnp.NPY_DATETIME)

# cdef double[:] _unixtime(cnp.ndarray dt) noexcept:
#     cdef double[:] ut# = dt.astype(np.float64) // 1e9 # type: ignore
#     ut = cnp.PyArray_Cast(dt, cnp.NPY_DOUBLE) // 1e9
#     return ut

# cdef extern from "numpy":
#     NPY_DOUBLE
#     NPY_DATETIME
obj = np.asanyarray(data, dtype="datetime64[ns]")
cnp.PyArray_Cast(obj, cnp.NPY_DOUBLE)
cdef astype_year(x):
    return cnp.PyArray_Cast(x, cnp.NPY_DATETIMEUNIT.NPY_FR_Y)

print(
    astype_year(obj),
    obj.astype('datetime64[Y]'),

    cnp.NPY_DATETIMEUNIT.NPY_FR_ns,
    # cnp.NPY_DATETIME,
    # cnp.NPY_DOUBLE,
    # # cnp.get_datetime64_value(dtarray(data)),
    # dtarray(data).astype(np.float64) // 1e9 == np.asanyarray(_unixtime(dtarray(data)))
    

)



[ True  True] ['2022' '2022'] 10


In [6]:
import numpy as np
np.datetime64
np.dtype
UT0 = np.datetime64('1970-01-01T00:00:00')
dt = UT0
dt.astype("datetime64[Y]").astype(float), dt.astype("datetime64[M]").astype(int) ,UT0


(0.0, 0, numpy.datetime64('1970-01-01T00:00:00'))

In [363]:
import numpy as np
from pathlib import Path
import os
PACKAGE_DIR = "src"
PROJECT_NAME = "fast_spa"
ROOT_DIR =  Path(PACKAGE_DIR)

compiler_directives: dict[str, int | bool] = {"language_level": 3}
define_macros: list[tuple[str, str | None]] = [("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")]

# if TEST:
#     # in order to compile the cython code for test coverage
#     # we need to include the following compiler directives...
#     compiler_directives.update({"linetrace": True, "profile": True})
#     # and include the following trace macros
#     define_macros.extend([("CYTHON_TRACE", "1"), ("CYTHON_TRACE_NOGIL", "1")])

import glob
def get_sources(pattern: str) -> list[str]:
    # with os.path
    return glob.glob(pattern, recursive=True)
    # return [os.path.join(root, file) for root, _, files in os.walk(ROOT_DIR) for file in files if file.endswith(pattern)]

    return [file.as_posix() for file in ROOT_DIR.rglob(pattern)]

get_sources("src/fast_spa/_lib/*.pyx")

['src/fast_spa/_lib/tables.pyx', 'src/fast_spa/_lib/spa.pyx']

In [16]:
L0 = np.array(
    [
        [175347046.0, 0.0, 0.0],
        [3341656.0, 4.6692568, 6283.07585],
        [34894.0, 4.6261, 12566.1517],
        [3497.0, 2.7441, 5753.3849],
        [3418.0, 2.8289, 3.5231],
        [3136.0, 3.6277, 77713.7715],
        [2676.0, 4.4181, 7860.4194],
        [2343.0, 6.1352, 3930.2097],
        [1324.0, 0.7425, 11506.7698],
        [1273.0, 2.0371, 529.691],
        [1199.0, 1.1096, 1577.3435],
        [990.0, 5.233, 5884.927],
        [902.0, 2.045, 26.298],
        [857.0, 3.508, 398.149],
        [780.0, 1.179, 5223.694],
        [753.0, 2.533, 5507.553],
        [505.0, 4.583, 18849.228],
        [492.0, 4.205, 775.523],
        [357.0, 2.92, 0.067],
        [317.0, 5.849, 11790.629],
        [284.0, 1.899, 796.298],
        [271.0, 0.315, 10977.079],
        [243.0, 0.345, 5486.778],
        [206.0, 4.806, 2544.314],
        [205.0, 1.869, 5573.143],
        [202.0, 2.458, 6069.777],
        [156.0, 0.833, 213.299],
        [132.0, 3.411, 2942.463],
        [126.0, 1.083, 20.775],
        [115.0, 0.645, 0.98],
        [103.0, 0.636, 4694.003],
        [102.0, 0.976, 15720.839],
        [102.0, 4.267, 7.114],
        [99.0, 6.21, 2146.17],
        [98.0, 0.68, 155.42],
        [86.0, 5.98, 161000.69],
        [85.0, 1.3, 6275.96],
        [85.0, 3.67, 71430.7],
        [80.0, 1.81, 17260.15],
        [79.0, 3.04, 12036.46],
        [75.0, 1.76, 5088.63],
        [74.0, 3.5, 3154.69],
        [74.0, 4.68, 801.82],
        [70.0, 0.83, 9437.76],
        [62.0, 3.98, 8827.39],
        [61.0, 1.82, 7084.9],
        [57.0, 2.78, 6286.6],
        [56.0, 4.39, 14143.5],
        [56.0, 3.47, 6279.55],
        [52.0, 0.19, 12139.55],
        [52.0, 1.33, 1748.02],
        [51.0, 0.28, 5856.48],
        [49.0, 0.49, 1194.45],
        [41.0, 5.37, 8429.24],
        [41.0, 2.4, 19651.05],
        [39.0, 6.17, 10447.39],
        [37.0, 6.04, 10213.29],
        [37.0, 2.57, 1059.38],
        [36.0, 1.71, 2352.87],
        [36.0, 1.78, 6812.77],
        [33.0, 0.59, 17789.85],
        [30.0, 0.44, 83996.85],
        [30.0, 2.74, 1349.87],
        [25.0, 3.16, 4690.48],
    ]
)
L1 = np.array(
    [
        [628331966747.0, 0.0, 0.0],
        [206059.0, 2.678235, 6283.07585],
        [4303.0, 2.6351, 12566.1517],
        [425.0, 1.59, 3.523],
        [119.0, 5.796, 26.298],
        [109.0, 2.966, 1577.344],
        [93.0, 2.59, 18849.23],
        [72.0, 1.14, 529.69],
        [68.0, 1.87, 398.15],
        [67.0, 4.41, 5507.55],
        [59.0, 2.89, 5223.69],
        [56.0, 2.17, 155.42],
        [45.0, 0.4, 796.3],
        [36.0, 0.47, 775.52],
        [29.0, 2.65, 7.11],
        [21.0, 5.34, 0.98],
        [19.0, 1.85, 5486.78],
        [19.0, 4.97, 213.3],
        [17.0, 2.99, 6275.96],
        [16.0, 0.03, 2544.31],
        [16.0, 1.43, 2146.17],
        [15.0, 1.21, 10977.08],
        [12.0, 2.83, 1748.02],
        [12.0, 3.26, 5088.63],
        [12.0, 5.27, 1194.45],
        [12.0, 2.08, 4694.0],
        [11.0, 0.77, 553.57],
        [10.0, 1.3, 6286.6],
        [10.0, 4.24, 1349.87],
        [9.0, 2.7, 242.73],
        [9.0, 5.64, 951.72],
        [8.0, 5.3, 2352.87],
        [6.0, 2.65, 9437.76],
        [6.0, 4.67, 4690.48],
    ]
)
L2 = np.array(
    [
        [52919.0, 0.0, 0.0],
        [8720.0, 1.0721, 6283.0758],
        [309.0, 0.867, 12566.152],
        [27.0, 0.05, 3.52],
        [16.0, 5.19, 26.3],
        [16.0, 3.68, 155.42],
        [10.0, 0.76, 18849.23],
        [9.0, 2.06, 77713.77],
        [7.0, 0.83, 775.52],
        [5.0, 4.66, 1577.34],
        [4.0, 1.03, 7.11],
        [4.0, 3.44, 5573.14],
        [3.0, 5.14, 796.3],
        [3.0, 6.05, 5507.55],
        [3.0, 1.19, 242.73],
        [3.0, 6.12, 529.69],
        [3.0, 0.31, 398.15],
        [3.0, 2.28, 553.57],
        [2.0, 4.38, 5223.69],
        [2.0, 3.75, 0.98],
    ]
)
L3 = np.array(
    [
        [289.0, 5.844, 6283.076],
        [35.0, 0.0, 0.0],
        [17.0, 5.49, 12566.15],
        [3.0, 5.2, 155.42],
        [1.0, 4.72, 3.52],
        [1.0, 5.3, 18849.23],
        [1.0, 5.97, 242.73],
    ]
)
L4 = np.array([[114.0, 3.142, 0.0], [8.0, 4.13, 6283.08], [1.0, 3.84, 12566.15]])
L5 = np.array([[1.0, 3.14, 0.0]])


# heliocentric latitude coefficients
B0 = np.array(
    [
        [280.0, 3.199, 84334.662],
        [102.0, 5.422, 5507.553],
        [80.0, 3.88, 5223.69],
        [44.0, 3.7, 2352.87],
        [32.0, 4.0, 1577.34],
    ]
)
B1 = np.array([[9.0, 3.9, 5507.55], [6.0, 1.73, 5223.69]])


# heliocentric radius coefficients
R0 = np.array(
    [
        [100013989.0, 0.0, 0.0],
        [1670700.0, 3.0984635, 6283.07585],
        [13956.0, 3.05525, 12566.1517],
        [3084.0, 5.1985, 77713.7715],
        [1628.0, 1.1739, 5753.3849],
        [1576.0, 2.8469, 7860.4194],
        [925.0, 5.453, 11506.77],
        [542.0, 4.564, 3930.21],
        [472.0, 3.661, 5884.927],
        [346.0, 0.964, 5507.553],
        [329.0, 5.9, 5223.694],
        [307.0, 0.299, 5573.143],
        [243.0, 4.273, 11790.629],
        [212.0, 5.847, 1577.344],
        [186.0, 5.022, 10977.079],
        [175.0, 3.012, 18849.228],
        [110.0, 5.055, 5486.778],
        [98.0, 0.89, 6069.78],
        [86.0, 5.69, 15720.84],
        [86.0, 1.27, 161000.69],
        [65.0, 0.27, 17260.15],
        [63.0, 0.92, 529.69],
        [57.0, 2.01, 83996.85],
        [56.0, 5.24, 71430.7],
        [49.0, 3.25, 2544.31],
        [47.0, 2.58, 775.52],
        [45.0, 5.54, 9437.76],
        [43.0, 6.01, 6275.96],
        [39.0, 5.36, 4694.0],
        [38.0, 2.39, 8827.39],
        [37.0, 0.83, 19651.05],
        [37.0, 4.9, 12139.55],
        [36.0, 1.67, 12036.46],
        [35.0, 1.84, 2942.46],
        [33.0, 0.24, 7084.9],
        [32.0, 0.18, 5088.63],
        [32.0, 1.78, 398.15],
        [28.0, 1.21, 6286.6],
        [28.0, 1.9, 6279.55],
        [26.0, 4.59, 10447.39],
    ]
)
R1 = np.array(
    [
        [103019.0, 1.10749, 6283.07585],
        [1721.0, 1.0644, 12566.1517],
        [702.0, 3.142, 0.0],
        [32.0, 1.02, 18849.23],
        [31.0, 2.84, 5507.55],
        [25.0, 1.32, 5223.69],
        [18.0, 1.42, 1577.34],
        [10.0, 5.91, 10977.08],
        [9.0, 1.42, 6275.96],
        [9.0, 0.27, 5486.78],
    ]
)
R2 = np.array(
    [
        [4359.0, 5.7846, 6283.0758],
        [124.0, 5.579, 12566.152],
        [12.0, 3.14, 0.0],
        [9.0, 3.63, 77713.77],
        [6.0, 1.87, 5573.14],
        [3.0, 5.47, 18849.23],
    ]
)
R3 = np.array([[145.0, 4.273, 6283.076], [7.0, 3.92, 12566.15]])
R4 = np.array([[4.0, 2.56, 6283.08]])


# longitude and obliquity nutation coefficients
NUTATION_ABCD_ARRAY = np.array(
    [
        [-171996, -174.2, 92025, 8.9],
        [-13187, -1.6, 5736, -3.1],
        [-2274, -0.2, 977, -0.5],
        [2062, 0.2, -895, 0.5],
        [1426, -3.4, 54, -0.1],
        [712, 0.1, -7, 0],
        [-517, 1.2, 224, -0.6],
        [-386, -0.4, 200, 0],
        [-301, 0, 129, -0.1],
        [217, -0.5, -95, 0.3],
        [-158, 0, 0, 0],
        [129, 0.1, -70, 0],
        [123, 0, -53, 0],
        [63, 0, 0, 0],
        [63, 0.1, -33, 0],
        [-59, 0, 26, 0],
        [-58, -0.1, 32, 0],
        [-51, 0, 27, 0],
        [48, 0, 0, 0],
        [46, 0, -24, 0],
        [-38, 0, 16, 0],
        [-31, 0, 13, 0],
        [29, 0, 0, 0],
        [29, 0, -12, 0],
        [26, 0, 0, 0],
        [-22, 0, 0, 0],
        [21, 0, -10, 0],
        [17, -0.1, 0, 0],
        [16, 0, -8, 0],
        [-16, 0.1, 7, 0],
        [-15, 0, 9, 0],
        [-13, 0, 7, 0],
        [-12, 0, 6, 0],
        [11, 0, 0, 0],
        [-10, 0, 5, 0],
        [-8, 0, 3, 0],
        [7, 0, -3, 0],
        [-7, 0, 0, 0],
        [-7, 0, 3, 0],
        [-7, 0, 3, 0],
        [6, 0, 0, 0],
        [6, 0, -3, 0],
        [6, 0, -3, 0],
        [-6, 0, 3, 0],
        [-6, 0, 3, 0],
        [5, 0, 0, 0],
        [-5, 0, 3, 0],
        [-5, 0, 3, 0],
        [-5, 0, 3, 0],
        [4, 0, 0, 0],
        [4, 0, 0, 0],
        [4, 0, 0, 0],
        [-4, 0, 0, 0],
        [-4, 0, 0, 0],
        [-4, 0, 0, 0],
        [3, 0, 0, 0],
        [-3, 0, 0, 0],
        [-3, 0, 0, 0],
        [-3, 0, 0, 0],
        [-3, 0, 0, 0],
        [-3, 0, 0, 0],
        [-3, 0, 0, 0],
        [-3, 0, 0, 0],
    ]
)

NUTATION_YTERM_ARRAY = np.array(
    [
        [0, 0, 0, 0, 1],
        [-2, 0, 0, 2, 2],
        [0, 0, 0, 2, 2],
        [0, 0, 0, 0, 2],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [-2, 1, 0, 2, 2],
        [0, 0, 0, 2, 1],
        [0, 0, 1, 2, 2],
        [-2, -1, 0, 2, 2],
        [-2, 0, 1, 0, 0],
        [-2, 0, 0, 2, 1],
        [0, 0, -1, 2, 2],
        [2, 0, 0, 0, 0],
        [0, 0, 1, 0, 1],
        [2, 0, -1, 2, 2],
        [0, 0, -1, 0, 1],
        [0, 0, 1, 2, 1],
        [-2, 0, 2, 0, 0],
        [0, 0, -2, 2, 1],
        [2, 0, 0, 2, 2],
        [0, 0, 2, 2, 2],
        [0, 0, 2, 0, 0],
        [-2, 0, 1, 2, 2],
        [0, 0, 0, 2, 0],
        [-2, 0, 0, 2, 0],
        [0, 0, -1, 2, 1],
        [0, 2, 0, 0, 0],
        [2, 0, -1, 0, 1],
        [-2, 2, 0, 2, 2],
        [0, 1, 0, 0, 1],
        [-2, 0, 1, 0, 1],
        [0, -1, 0, 0, 1],
        [0, 0, 2, -2, 0],
        [2, 0, -1, 2, 1],
        [2, 0, 1, 2, 2],
        [0, 1, 0, 2, 2],
        [-2, 1, 1, 0, 0],
        [0, -1, 0, 2, 2],
        [2, 0, 0, 2, 1],
        [2, 0, 1, 0, 0],
        [-2, 0, 2, 2, 2],
        [-2, 0, 1, 2, 1],
        [2, 0, -2, 0, 1],
        [2, 0, 0, 0, 1],
        [0, -1, 1, 0, 0],
        [-2, -1, 0, 2, 1],
        [-2, 0, 0, 0, 1],
        [0, 0, 2, 2, 1],
        [-2, 0, 2, 0, 1],
        [-2, 1, 0, 2, 1],
        [0, 0, 1, -2, 0],
        [-1, 0, 1, 0, 0],
        [-2, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 2, 0],
        [0, 0, -2, 2, 2],
        [-1, -1, 1, 0, 0],
        [0, 1, 1, 0, 0],
        [0, -1, 1, 2, 2],
        [2, -1, -1, 2, 2],
        [0, 0, 3, 2, 2],
        [2, -1, 0, 2, 2],
    ]
)




In [18]:
import pvlib
def sum_mult_cos_add_mult(arr, x):
    # shared calculation used for heliocentric longitude, latitude, and radius
    s = 0.0
    for row in range(arr.shape[0]):
        s += arr[row, 0] * np.cos(arr[row, 1] + arr[row, 2] * x)
    return s



def heliocentric_longitude(jme):
    l0 = sum_mult_cos_add_mult(L0, jme)
    l1 = sum_mult_cos_add_mult(L1, jme)
    l2 = sum_mult_cos_add_mult(L2, jme)
    l3 = sum_mult_cos_add_mult(L3, jme)
    l4 = sum_mult_cos_add_mult(L4, jme)
    l5 = sum_mult_cos_add_mult(L5, jme)

    l_rad = (l0 + l1 * jme + l2 * jme**2 + l3 * jme**3 + l4 * jme**4 + l5 * jme**5) / 10**8
    l = np.rad2deg(l_rad)
    return l % 360



def heliocentric_latitude(jme):
    b0 = sum_mult_cos_add_mult(B0, jme)
    b1 = sum_mult_cos_add_mult(B1, jme)

    b_rad = (b0 + b1 * jme) / 10**8
    b = np.rad2deg(b_rad)
    return b



def heliocentric_radius_vector(jme):
    r0 = sum_mult_cos_add_mult(R0, jme)
    r1 = sum_mult_cos_add_mult(R1, jme)
    r2 = sum_mult_cos_add_mult(R2, jme)
    r3 = sum_mult_cos_add_mult(R3, jme)
    r4 = sum_mult_cos_add_mult(R4, jme)
    

    r = (r0 + r1 * jme + r2 * jme**2 + r3 * jme**3 + r4 * jme**4) / 10**8
    return r

dates = np.array(["2019-01-01 00:00:00", "2019-01-01 00:10:00"], dtype="datetime64[ns]")
def to_unix_time(x) -> np.ndarray:
    return np.asanyarray(x, dtype="datetime64[ns]").astype(np.float64) // 1e9

heliocentric_radius_vector(to_unix_time(dates)) == pvlib.spa.heliocentric_radius_vector(to_unix_time(dates))

[9.88323526e+07 1.00805942e+08] [-38682.18648339  60798.48861795] [ 4207.35585376 -4353.78376331] [ 136.41260426 -130.38748292] [-3.43717922 -2.51963171]


array([ True,  True])

In [ ]:


def calculate_deltat(year, month):
    """Calculate the difference between Terrestrial Dynamical Time (TD)
    and Universal Time (UT).

    Note: This function is not yet compatible for calculations using
    Numba.

    Equations taken from http://eclipse.gsfc.nasa.gov/SEcat5/deltatpoly.html
    """

    y = year + (month - 0.5) / 12

    deltat = np.where(year < -500, -20 + 32 * ((y - 1820) / 100) ** 2, 0)
    return np.select(
        [
            (-500 <= year) & (year < 500),
            (1600 <= year) & (year < 1700),
        ],
        [
            (10583.6 - 1014.41 * (y / 100) + 33.78311 * (y / 100) ** 2 - 5.952053 * (y / 100) ** 3 - 0.1798452 * (y / 100) ** 4 + 0.022174192 * (y / 100) ** 5 + 0.0090316521 * (y / 100) ** 6),
            (120 - 0.9808 * (y - 1600) - 0.01532 * (y - 1600) ** 2 + (y - 1600) ** 3 / 7129),
        ],
        deltat,
    )
    # deltat = np.where(
    #     (-500 <= year) & (year < 500),
    #     deltat,
    # )

    # deltat = np.where(
    #     (500 <= year) & (year < 1600),
    #     1574.2
    #     - 556.01 * ((y - 1000) / 100)
    #     + 71.23472 * ((y - 1000) / 100) ** 2
    #     + 0.319781 * ((y - 1000) / 100) ** 3
    #     - 0.8503463 * ((y - 1000) / 100) ** 4
    #     - 0.005050998 * ((y - 1000) / 100) ** 5
    #     + 0.0083572073 * ((y - 1000) / 100) ** 6,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1600 <= year) & (year < 1700),
    #     120 - 0.9808 * (y - 1600) - 0.01532 * (y - 1600) ** 2 + (y - 1600) ** 3 / 7129,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1700 <= year) & (year < 1800),
    #     8.83
    #     + 0.1603 * (y - 1700)
    #     - 0.0059285 * (y - 1700) ** 2
    #     + 0.00013336 * (y - 1700) ** 3
    #     - (y - 1700) ** 4 / 1174000,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1800 <= year) & (year < 1860),
    #     13.72
    #     - 0.332447 * (y - 1800)
    #     + 0.0068612 * (y - 1800) ** 2
    #     + 0.0041116 * (y - 1800) ** 3
    #     - 0.00037436 * (y - 1800) ** 4
    #     + 0.0000121272 * (y - 1800) ** 5
    #     - 0.0000001699 * (y - 1800) ** 6
    #     + 0.000000000875 * (y - 1800) ** 7,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1860 <= year) & (year < 1900),
    #     7.62
    #     + 0.5737 * (y - 1860)
    #     - 0.251754 * (y - 1860) ** 2
    #     + 0.01680668 * (y - 1860) ** 3
    #     - 0.0004473624 * (y - 1860) ** 4
    #     + (y - 1860) ** 5 / 233174,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1900 <= year) & (year < 1920),
    #     -2.79
    #     + 1.494119 * (y - 1900)
    #     - 0.0598939 * (y - 1900) ** 2
    #     + 0.0061966 * (y - 1900) ** 3
    #     - 0.000197 * (y - 1900) ** 4,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1920 <= year) & (year < 1941),
    #     21.20 + 0.84493 * (y - 1920) - 0.076100 * (y - 1920) ** 2 + 0.0020936 * (y - 1920) ** 3,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1941 <= year) & (year < 1961),
    #     29.07 + 0.407 * (y - 1950) - (y - 1950) ** 2 / 233 + (y - 1950) ** 3 / 2547,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1961 <= year) & (year < 1986),
    #     45.45 + 1.067 * (y - 1975) - (y - 1975) ** 2 / 260 - (y - 1975) ** 3 / 718,
    #     deltat,
    # )

    # deltat = np.where(
    #     (1986 <= year) & (year < 2005),
    #     63.86
    #     + 0.3345 * (y - 2000)
    #     - 0.060374 * (y - 2000) ** 2
    #     + 0.0017275 * (y - 2000) ** 3
    #     + 0.000651814 * (y - 2000) ** 4
    #     + 0.00002373599 * (y - 2000) ** 5,
    #     deltat,
    # )

    # deltat = np.where(
    #     (2005 <= year) & (year < 2050), 62.92 + 0.32217 * (y - 2000) + 0.005589 * (y - 2000) ** 2, deltat
    # )

    # deltat = np.where((2050 <= year) & (year < 2150), -20 + 32 * ((y - 1820) / 100) ** 2 - 0.5628 * (2150 - y), deltat)

    # deltat = np.where(year >= 2150, -20 + 32 * ((y - 1820) / 100) ** 2, deltat)

    # deltat = deltat.item() if np.isscalar(year) & np.isscalar(month) else deltat

    # return deltat


In [137]:
x = [
    "2019-01-01 01:00:00",
]
ut = np.asanyarray(x, dtype="datetime64[ns]").ravel().astype(np.float64) // 1e9
jd = ut * 1.0 / 86400 + 2440587.5
print(jd, ut)

[2458484.54166667] [1.5463044e+09]


In [202]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION

cimport numpy as cnp
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np
cimport cython

cnp.import_array()

ctypedef fused floating:
    f32
    f64

# =============================================================================
#  Table A4.2. Earth Periodic Terms
# =============================================================================
EARTH_PERIODIC_LONGITUDE_TERMS = (
    (   # L0
        (175347046.0, 0.0, 0.0),
        (3341656.0, 4.6692568, 6283.07585),
        (34894.0, 4.6261, 12566.1517),
        (3497.0, 2.7441, 5753.3849),
        (3418.0, 2.8289, 3.5231),
        (3136.0, 3.6277, 77713.7715),
        (2676.0, 4.4181, 7860.4194),
        (2343.0, 6.1352, 3930.2097),
        (1324.0, 0.7425, 11506.7698),
        (1273.0, 2.0371, 529.691),
        (1199.0, 1.1096, 1577.3435),
        (990.0, 5.233, 5884.927),
        (902.0, 2.045, 26.298),
        (857.0, 3.508, 398.149),
        (780.0, 1.179, 5223.694),
        (753.0, 2.533, 5507.553),
        (505.0, 4.583, 18849.228),
        (492.0, 4.205, 775.523),
        (357.0, 2.92, 0.067),
        (317.0, 5.849, 11790.629),
        (284.0, 1.899, 796.298),
        (271.0, 0.315, 10977.079),
        (243.0, 0.345, 5486.778),
        (206.0, 4.806, 2544.314),
        (205.0, 1.869, 5573.143),
        (202.0, 2.458, 6069.777),
        (156.0, 0.833, 213.299),
        (132.0, 3.411, 2942.463),
        (126.0, 1.083, 20.775),
        (115.0, 0.645, 0.98),
        (103.0, 0.636, 4694.003),
        (102.0, 0.976, 15720.839),
        (102.0, 4.267, 7.114),
        (99.0, 6.21, 2146.17),
        (98.0, 0.68, 155.42),
        (86.0, 5.98, 161000.69),
        (85.0, 1.3, 6275.96),
        (85.0, 3.67, 71430.7),
        (80.0, 1.81, 17260.15),
        (79.0, 3.04, 12036.46),
        (75.0, 1.76, 5088.63),
        (74.0, 3.5, 3154.69),
        (74.0, 4.68, 801.82),
        (70.0, 0.83, 9437.76),
        (62.0, 3.98, 8827.39),
        (61.0, 1.82, 7084.9),
        (57.0, 2.78, 6286.6),
        (56.0, 4.39, 14143.5),
        (56.0, 3.47, 6279.55),
        (52.0, 0.19, 12139.55),
        (52.0, 1.33, 1748.02),
        (51.0, 0.28, 5856.48),
        (49.0, 0.49, 1194.45),
        (41.0, 5.37, 8429.24),
        (41.0, 2.4, 19651.05),
        (39.0, 6.17, 10447.39),
        (37.0, 6.04, 10213.29),
        (37.0, 2.57, 1059.38),
        (36.0, 1.71, 2352.87),
        (36.0, 1.78, 6812.77),
        (33.0, 0.59, 17789.85),
        (30.0, 0.44, 83996.85),
        (30.0, 2.74, 1349.87),
        (25.0, 3.16, 4690.48),
    ),
    (   # L1
        (628331966747.0, 0.0, 0.0),
        (206059.0, 2.678235, 6283.07585),
        (4303.0, 2.6351, 12566.1517),
        (425.0, 1.59, 3.523),
        (119.0, 5.796, 26.298),
        (109.0, 2.966, 1577.344),
        (93.0, 2.59, 18849.23),
        (72.0, 1.14, 529.69),
        (68.0, 1.87, 398.15),
        (67.0, 4.41, 5507.55),
        (59.0, 2.89, 5223.69),
        (56.0, 2.17, 155.42),
        (45.0, 0.4, 796.3),
        (36.0, 0.47, 775.52),
        (29.0, 2.65, 7.11),
        (21.0, 5.34, 0.98),
        (19.0, 1.85, 5486.78),
        (19.0, 4.97, 213.3),
        (17.0, 2.99, 6275.96),
        (16.0, 0.03, 2544.31),
        (16.0, 1.43, 2146.17),
        (15.0, 1.21, 10977.08),
        (12.0, 2.83, 1748.02),
        (12.0, 3.26, 5088.63),
        (12.0, 5.27, 1194.45),
        (12.0, 2.08, 4694.0),
        (11.0, 0.77, 553.57),
        (10.0, 1.3, 6286.6),
        (10.0, 4.24, 1349.87),
        (9.0, 2.7, 242.73),
        (9.0, 5.64, 951.72),
        (8.0, 5.3, 2352.87),
        (6.0, 2.65, 9437.76),
        (6.0, 4.67, 4690.48),
    ),
    (   # L2
        (52919.0, 0.0, 0.0),
        (8720.0, 1.0721, 6283.0758),
        (309.0, 0.867, 12566.152),
        (27.0, 0.05, 3.52),
        (16.0, 5.19, 26.3),
        (16.0, 3.68, 155.42),
        (10.0, 0.76, 18849.23),
        (9.0, 2.06, 77713.77),
        (7.0, 0.83, 775.52),
        (5.0, 4.66, 1577.34),
        (4.0, 1.03, 7.11),
        (4.0, 3.44, 5573.14),
        (3.0, 5.14, 796.3),
        (3.0, 6.05, 5507.55),
        (3.0, 1.19, 242.73),
        (3.0, 6.12, 529.69),
        (3.0, 0.31, 398.15),
        (3.0, 2.28, 553.57),
        (2.0, 4.38, 5223.69),
        (2.0, 3.75, 0.98),
    ),
    (   # L3
        (289.0, 5.844, 6283.076),
        (35.0, 0.0, 0.0),
        (17.0, 5.49, 12566.15),
        (3.0, 5.2, 155.42),
        (1.0, 4.72, 3.52),
        (1.0, 5.3, 18849.23),
        (1.0, 5.97, 242.73),
    ),
    (   # L4
        (114.0, 3.142, 0.0),
        (8.0, 4.13, 6283.08),
        (1.0, 3.84, 12566.15),
    ),
    (   # L5
        (1.0, 3.14, 0.0),
    ),
)

EARTH_PERIODIC_LATITUDE_TERMS = (
    (   # B0
        (280.0, 3.199, 84334.662),
        (102.0, 5.422, 5507.553),
        (80.0, 3.88, 5223.69),
        (44.0, 3.7, 2352.87),
        (32.0, 4.0, 1577.34),
    ),
    (   # B1
        (9.0, 3.9, 5507.55),
        (6.0, 1.73, 5223.69),
    ),
)

EARTH_PERIODIC_RADIUS_VECTOR_TERMS = ( 
    (   # R0
        (100013989.0, 0.0, 0.0),
        (1670700.0, 3.0984635, 6283.07585),
        (13956.0, 3.05525, 12566.1517),
        (3084.0, 5.1985, 77713.7715),
        (1628.0, 1.1739, 5753.3849),
        (1576.0, 2.8469, 7860.4194),
        (925.0, 5.453, 11506.77),
        (542.0, 4.564, 3930.21),
        (472.0, 3.661, 5884.927),
        (346.0, 0.964, 5507.553),
        (329.0, 5.9, 5223.694),
        (307.0, 0.299, 5573.143),
        (243.0, 4.273, 11790.629),
        (212.0, 5.847, 1577.344),
        (186.0, 5.022, 10977.079),
        (175.0, 3.012, 18849.228),
        (110.0, 5.055, 5486.778),
        (98.0, 0.89, 6069.78),
        (86.0, 5.69, 15720.84),
        (86.0, 1.27, 161000.69),
        (65.0, 0.27, 17260.15),
        (63.0, 0.92, 529.69),
        (57.0, 2.01, 83996.85),
        (56.0, 5.24, 71430.7),
        (49.0, 3.25, 2544.31),
        (47.0, 2.58, 775.52),
        (45.0, 5.54, 9437.76),
        (43.0, 6.01, 6275.96),
        (39.0, 5.36, 4694.0),
        (38.0, 2.39, 8827.39),
        (37.0, 0.83, 19651.05),
        (37.0, 4.9, 12139.55),
        (36.0, 1.67, 12036.46),
        (35.0, 1.84, 2942.46),
        (33.0, 0.24, 7084.9),
        (32.0, 0.18, 5088.63),
        (32.0, 1.78, 398.15),
        (28.0, 1.21, 6286.6),
        (28.0, 1.9, 6279.55),
        (26.0, 4.59, 10447.39),
    ),
    (   # R1
        (103019.0, 1.10749, 6283.07585),
        (1721.0, 1.0644, 12566.1517),
        (702.0, 3.142, 0.0),
        (32.0, 1.02, 18849.23),
        (31.0, 2.84, 5507.55),
        (25.0, 1.32, 5223.69),
        (18.0, 1.42, 1577.34),
        (10.0, 5.91, 10977.08),
        (9.0, 1.42, 6275.96),
        (9.0, 0.27, 5486.78),
    ),
    (   # R2
        (4359.0, 5.7846, 6283.0758),
        (124.0, 5.579, 12566.152),
        (12.0, 3.14, 0.0),
        (9.0, 3.63, 77713.77),
        (6.0, 1.87, 5573.14),
        (3.0, 5.47, 18849.23),
    ),
    (   # R3
        (145.0, 4.273, 6283.076),
        (7.0, 3.92, 12566.15),
    ),
    (   # R4
        (4.0, 2.56, 6283.08),
    ),
)
NUM_LONGITUDE_TERMS = len(EARTH_PERIODIC_LONGITUDE_TERMS)
NUM_LATITUDE_TERMS = len(EARTH_PERIODIC_LATITUDE_TERMS)
NUM_RADIUS_VECTOR_TERMS = len(EARTH_PERIODIC_RADIUS_VECTOR_TERMS)


NUTATION_ABCD_ARRAY = (
    (-171996.0, -174.2, 92025.0, 8.9),
    (-13187.0, -1.6, 5736.0, -3.1),
    (-2274.0, -0.2, 977.0, -0.5),
    (2062.0, 0.2, -895.0, 0.5),
    (1426.0, -3.4, 54.0, -0.1),
    (712.0, 0.1, -7.0, 0.0),
    (-517.0, 1.2, 224.0, -0.6),
    (-386.0, -0.4, 200.0, 0.0),
    (-301.0, 0.0, 129.0, -0.1),
    (217.0, -0.5, -95.0, 0.3),
    (-158.0, 0.0, 0.0, 0.0),
    (129.0, 0.1, -70.0, 0.0),
    (123.0, 0.0, -53.0, 0.0),
    (63.0, 0.0, 0.0, 0.0),
    (63.0, 0.1, -33.0, 0.0),
    (-59.0, 0.0, 26.0, 0.0),
    (-58.0, -0.1, 32.0, 0.0),
    (-51.0, 0.0, 27.0, 0.0),
    (48.0, 0.0, 0.0, 0.0),
    (46.0, 0.0, -24.0, 0.0),
    (-38.0, 0.0, 16.0, 0.0),
    (-31.0, 0.0, 13.0, 0.0),
    (29.0, 0.0, 0.0, 0.0),
    (29.0, 0.0, -12.0, 0.0),
    (26.0, 0.0, 0.0, 0.0),
    (-22.0, 0.0, 0.0, 0.0),
    (21.0, 0.0, -10.0, 0.0),
    (17.0, -0.1, 0.0, 0.0),
    (16.0, 0.0, -8.0, 0.0),
    (-16.0, 0.1, 7.0, 0.0),
    (-15.0, 0.0, 9.0, 0.0),
    (-13.0, 0.0, 7.0, 0.0),
    (-12.0, 0.0, 6.0, 0.0),
    (11.0, 0.0, 0.0, 0.0),
    (-10.0, 0.0, 5.0, 0.0),
    (-8.0, 0.0, 3.0, 0.0),
    (7.0, 0.0, -3.0, 0.0),
    (-7.0, 0.0, 0.0, 0.0),
    (-7.0, 0.0, 3.0, 0.0),
    (-7.0, 0.0, 3.0, 0.0),
    (6.0, 0.0, 0.0, 0.0),
    (6.0, 0.0, -3.0, 0.0),
    (6.0, 0.0, -3.0, 0.0),
    (-6.0, 0.0, 3.0, 0.0),
    (-6.0, 0.0, 3.0, 0.0),
    (5.0, 0.0, 0.0, 0.0),
    (-5.0, 0.0, 3.0, 0.0),
    (-5.0, 0.0, 3.0, 0.0),
    (-5.0, 0.0, 3.0, 0.0),
    (4.0, 0.0, 0.0, 0.0),
    (4.0, 0.0, 0.0, 0.0),
    (4.0, 0.0, 0.0, 0.0),
    (-4.0, 0.0, 0.0, 0.0),
    (-4.0, 0.0, 0.0, 0.0),
    (-4.0, 0.0, 0.0, 0.0),
    (3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0),
    (-3.0, 0.0, 0.0, 0.0)
)

# =============================================================================
# Table A4.3. Periodic Terms for the Nutation in Longitude and Obliquity
# =============================================================================
PERIODIC_TERMS_FOR_THE_NUTATION_IN_LONGITUDE_AND_OBLIQUITY = (
#   (Y0 Y1 Y2 Y3 Y4)
    (0, 0, 0, 0, 1),
    (-2, 0, 0, 2, 2),
    (0, 0, 0, 2, 2),
    (0, 0, 0, 0, 2),
    (0, 1, 0, 0, 0),
    (0, 0, 1, 0, 0),
    (-2, 1, 0, 2, 2),
    (0, 0, 0, 2, 1),
    (0, 0, 1, 2, 2),
    (-2, -1, 0, 2, 2),
    (-2, 0, 1, 0, 0),
    (-2, 0, 0, 2, 1),
    (0, 0, -1, 2, 2),
    (2, 0, 0, 0, 0),
    (0, 0, 1, 0, 1),
    (2, 0, -1, 2, 2),
    (0, 0, -1, 0, 1),
    (0, 0, 1, 2, 1),
    (-2, 0, 2, 0, 0),
    (0, 0, -2, 2, 1),
    (2, 0, 0, 2, 2),
    (0, 0, 2, 2, 2),
    (0, 0, 2, 0, 0),
    (-2, 0, 1, 2, 2),
    (0, 0, 0, 2, 0),
    (-2, 0, 0, 2, 0),
    (0, 0, -1, 2, 1),
    (0, 2, 0, 0, 0),
    (2, 0, -1, 0, 1),
    (-2, 2, 0, 2, 2),
    (0, 1, 0, 0, 1),
    (-2, 0, 1, 0, 1),
    (0, -1, 0, 0, 1),
    (0, 0, 2, -2, 0),
    (2, 0, -1, 2, 1),
    (2, 0, 1, 2, 2),
    (0, 1, 0, 2, 2),
    (-2, 1, 1, 0, 0),
    (0, -1, 0, 2, 2),
    (2, 0, 0, 2, 1),
    (2, 0, 1, 0, 0),
    (-2, 0, 2, 2, 2),
    (-2, 0, 1, 2, 1),
    (2, 0, -2, 0, 1),
    (2, 0, 0, 0, 1),
    (0, -1, 1, 0, 0),
    (-2, -1, 0, 2, 1),
    (-2, 0, 0, 0, 1),
    (0, 0, 2, 2, 1),
    (-2, 0, 2, 0, 1),
    (-2, 1, 0, 2, 1),
    (0, 0, 1, -2, 0),
    (-1, 0, 1, 0, 0),
    (-2, 1, 0, 0, 0),
    (1, 0, 0, 0, 0),
    (0, 0, 1, 2, 0),
    (0, 0, -2, 2, 2),
    (-1, -1, 1, 0, 0),
    (0, 1, 1, 0, 0),
    (0, -1, 1, 2, 2),
    (2, -1, -1, 2, 2),
    (0, 0, 3, 2, 2),
    (2, -1, 0, 2, 2)
)


# Table A4.2. Earth Periodic Terms
cdef _earth_periodic_terms(
    tuple[int, ...] shape,
    tuple[tuple[tuple[float, float, float], ...], ...] terms,
    NDArray jme, 
):
    cdef int n_term, n_rows, i, j
    cdef float a, b, c
    cdef NDArray out
    n_term = shape[0]
    
    out = np.zeros(shape, dtype=np.float64)
    for i in range(n_term):
        term = terms[i]
        n_rows = len(term)
        for j in range(n_rows):
            a, b, c = term[j]
            # 3.2.1. For each row of Table A4.2, calculate the term L0i (in radians), 
            out[i] += a * np.cos(b + c * jme)

    return out


cdef _earth_heliocentric_longitude_latitude_and_radius_vector(
    tuple[float, ...] shape,
    NDArray jme, 
):
    """
    3.2.	 Calculate the Earth heliocentric longitude, latitude, and radius vector (L, B, # and R): 
    “Heliocentric” means that the Earth position is calculated with respect to the center of the sun. 
    3.2.1. For each row of Table A4.2, calculate the term L0i (in radians), 
    L0 =	 A *cos ( B + C * JME) , (9) i i i i 
    where, 
    - i is the ith row for the term L0 in Table A4.2. 
    - Ai , Bi , and Ci are the values in the ith row and A, B, and C columns in Table 
    A4.2, for the term L0 (in radians). 
    3.2.2. Calculate the term L0 (in radians), 
    n 
    L0 = ∑ L0i ,	 (10) 
    i = 0 
    where n is the number of rows for the term L0 in Table A4.2. 
    3.2.3. Calculate the terms L1, L2, L3, L4, and L5 by using Equations 9 and 10 and 
    changing the 0 to 1, 2, 3, 4, and 5, and by using their corresponding values in"""
    cdef NDArray L, B, R, l0, l1, l2, l3, l4, l5, b0, b1, r0, r1, r2, r3, r4
    l0, l1, l2, l3, l4, l5 = _earth_periodic_terms(
        ((NUM_LONGITUDE_TERMS, ) +  shape),
        EARTH_PERIODIC_LONGITUDE_TERMS,
        jme,
    )
    L = np.rad2deg(
        (l0 + l1 * jme + l2 * jme**2 + l3 * jme**3 + l4 * jme**4 + l5 * jme**5) / 1e8
    )
    L %=  360

    b0, b1 = _earth_periodic_terms(
        ((NUM_LATITUDE_TERMS, ) +  shape),
        EARTH_PERIODIC_LATITUDE_TERMS,
        jme,
    )
    B = np.rad2deg((b0 + b1 * jme) / 10**8)

    # - radius vector (R) in astronomical units (AU)
    r0, r1, r2, r3, r4 = _earth_periodic_terms(
        ((NUM_RADIUS_VECTOR_TERMS, ) +  shape),
        EARTH_PERIODIC_RADIUS_VECTOR_TERMS,
        jme,
    )
    R = (r0 + r1 * jme + r2 * jme**2 + r3 * jme**3 + r4 * jme**4) / 1e8
    
    return L, B, R



def earth_periodic_terms(jme:np.ndarray) -> np.ndarray:
    return _earth_heliocentric_longitude_latitude_and_radius_vector(
        jme.shape,
        jme,
)


# =============================================================================
# Julian Day Conversion
# =============================================================================
@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_day(NDArray[f64, ndim=1] ut):
    cdef NDArray[f64, ndim=1] jd
    jd = ut * 1.0 / 86400 + 2440587.5
    return jd

@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_century(NDArray[f64, ndim=1] jd):
    cdef NDArray[f64, ndim=1] jc
    jc = (jd - 2451545) * 1.0 / 36525
    return jc
@cython.boundscheck(False)
@cython.wraparound(False)
def julian_century(NDArray[f64, ndim=1] ut):
    cdef NDArray[f64, ndim=1] jd, jc
    jd = _julian_day(ut)
    jc = _julian_century(jd)
    return jc

# - ephemeris
@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_ephemeris_day(NDArray[f64, ndim=1] jd, delta_t):
    cdef NDArray[f64, ndim=1] jde
    jde = jd + delta_t * 1.0 / 86400
    return jde

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_ephemeris_day(NDArray[f64, ndim=1] ut, NDArray[f64, ndim=1] delta_t):
    cdef NDArray[f64, ndim=1] jd, jde
    jd = _julian_day(ut)
    jde = _julian_ephemeris_day(jd, delta_t)
    return jde

@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_ephemeris_century(NDArray[f64, ndim=1] jde):
    cdef NDArray[f64, ndim=1] jce
    jce = (jde - 2451545) * 1.0 / 36525
    return jce

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_ephemeris_century(NDArray[f64, ndim=1] ut, NDArray[f64, ndim=1] delta_t):
    cdef NDArray[f64, ndim=1] jd, jde, jce
    jd = _julian_day(ut)
    jde = _julian_ephemeris_day(jd, delta_t)
    jce = _julian_ephemeris_century(jde)
    return jce

@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_ephemeris_millennium(NDArray[f64, ndim=1] jce):
    cdef NDArray[f64, ndim=1] jme
    jme = jce * 1.0 / 10
    return jme

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_ephemeris_millennium(NDArray[f64, ndim=1] ut, NDArray[f64, ndim=1] delta_t):
    cdef NDArray[f64, ndim=1] jd, jde, jce, jme
    jd = _julian_day(ut)
    jde = _julian_ephemeris_day(jd, delta_t)
    jce = _julian_ephemeris_century(jde)
    jme = _julian_ephemeris_millennium(jce)
    return jme


# =============================================================================
#
#
#
# =============================================================================
import pvlib
def unix_time(x):
    cdef NDArray[f64, ndim=1] ut
    out = np.asanyarray(x, dtype="datetime64[ns]").ravel().astype(np.float64) // 1e9
    return out

    
def test_time_conversion(date):
    dt = np.asanyarray(date, dtype="datetime64[ns]")
    year = dt.astype("datetime64[Y]").astype(int) + 1970
    month = dt.astype("datetime64[M]").astype(int) % 12 + 1
    ut = dt.astype(np.float64) // 1e9
    delta_t = pvlib.spa.calculate_deltat(year, month)
    print(delta_t)
    jd = pvlib.spa.julian_day(ut)
    assert np.all(jd == _julian_day(ut))
    
    jc = pvlib.spa.julian_century(jd)
    assert np.all(jc == julian_century(ut))
    
    jde = pvlib.spa.julian_ephemeris_day(jd, delta_t)
    assert np.all(jde == julian_ephemeris_day(ut, delta_t))
    
    jce = pvlib.spa.julian_ephemeris_century(jde)
    assert np.all(jce == julian_ephemeris_century(ut, delta_t))

    jme = pvlib.spa.julian_ephemeris_millennium(jce)
    assert np.all(jme == julian_ephemeris_millennium(ut, delta_t))
    print(jme)

def test_earth_periodic_terms(date):
    dt = np.asanyarray(date, dtype="datetime64[ns]")
    year = dt.astype("datetime64[Y]").astype(int) + 1970
    month = dt.astype("datetime64[M]").astype(int) % 12 + 1
    ut = dt.astype(np.float64) // 1e9
    delta_t = pvlib.spa.calculate_deltat(year, month)
    
    jme = julian_ephemeris_millennium(ut, delta_t)
    


    a = np.stack(earth_periodic_terms(jme))
    b = np.stack([
        pvlib.spa.heliocentric_longitude(jme),
        pvlib.spa.heliocentric_latitude(jme),
        pvlib.spa.heliocentric_radius_vector(jme),
    ])
    
    assert np.allclose(a, b, rtol=1e-5, atol=1e-5)
    
    

for dates in [
    ["2019-01-01 00:00:00"],
    ["2019-01-01 00:00:00", "2019-01-01 00:10:00"],
    ["2019-01-01 00:00:00", "2029-02-01 00:10:00", "2019-01-01 00:20:00"],
]:
    test_time_conversion(dates)
    test_earth_periodic_terms(dates)
    

In [ ]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
from cython.view cimport array as cvarray
# from cpython cimport array
# import array
cimport cython
from cython.parallel cimport prange
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np

cdef f64[:, :]

In [352]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
from cython.view cimport array as cvarray
cimport cython
from cython.parallel cimport prange
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np
from libc.math cimport cos, sin, sqrt
cdef f64[:, :] L0, L1, L2, L3, L4, L5, B0, B1, B2, B3, B4, B5, R1, R2, R3, R4, R5

L0 = np.array(
    [
        [175347046.0, 0.0, 0.0],
        [3341656.0, 4.6692568, 6283.07585],
        [34894.0, 4.6261, 12566.1517],
        [3497.0, 2.7441, 5753.3849],
        [3418.0, 2.8289, 3.5231],
        [3136.0, 3.6277, 77713.7715],
        [2676.0, 4.4181, 7860.4194],
        [2343.0, 6.1352, 3930.2097],
        [1324.0, 0.7425, 11506.7698],
        [1273.0, 2.0371, 529.691],
        [1199.0, 1.1096, 1577.3435],
        [990.0, 5.233, 5884.927],
        [902.0, 2.045, 26.298],
        [857.0, 3.508, 398.149],
        [780.0, 1.179, 5223.694],
        [753.0, 2.533, 5507.553],
        [505.0, 4.583, 18849.228],
        [492.0, 4.205, 775.523],
        [357.0, 2.92, 0.067],
        [317.0, 5.849, 11790.629],
        [284.0, 1.899, 796.298],
        [271.0, 0.315, 10977.079],
        [243.0, 0.345, 5486.778],
        [206.0, 4.806, 2544.314],
        [205.0, 1.869, 5573.143],
        [202.0, 2.458, 6069.777],
        [156.0, 0.833, 213.299],
        [132.0, 3.411, 2942.463],
        [126.0, 1.083, 20.775],
        [115.0, 0.645, 0.98],
        [103.0, 0.636, 4694.003],
        [102.0, 0.976, 15720.839],
        [102.0, 4.267, 7.114],
        [99.0, 6.21, 2146.17],
        [98.0, 0.68, 155.42],
        [86.0, 5.98, 161000.69],
        [85.0, 1.3, 6275.96],
        [85.0, 3.67, 71430.7],
        [80.0, 1.81, 17260.15],
        [79.0, 3.04, 12036.46],
        [75.0, 1.76, 5088.63],
        [74.0, 3.5, 3154.69],
        [74.0, 4.68, 801.82],
        [70.0, 0.83, 9437.76],
        [62.0, 3.98, 8827.39],
        [61.0, 1.82, 7084.9],
        [57.0, 2.78, 6286.6],
        [56.0, 4.39, 14143.5],
        [56.0, 3.47, 6279.55],
        [52.0, 0.19, 12139.55],
        [52.0, 1.33, 1748.02],
        [51.0, 0.28, 5856.48],
        [49.0, 0.49, 1194.45],
        [41.0, 5.37, 8429.24],
        [41.0, 2.4, 19651.05],
        [39.0, 6.17, 10447.39],
        [37.0, 6.04, 10213.29],
        [37.0, 2.57, 1059.38],
        [36.0, 1.71, 2352.87],
        [36.0, 1.78, 6812.77],
        [33.0, 0.59, 17789.85],
        [30.0, 0.44, 83996.85],
        [30.0, 2.74, 1349.87],
        [25.0, 3.16, 4690.48],
    ], 
    dtype=np.float64
)
L1 = np.array(
    [
        [628331966747.0, 0.0, 0.0],
        [206059.0, 2.678235, 6283.07585],
        [4303.0, 2.6351, 12566.1517],
        [425.0, 1.59, 3.523],
        [119.0, 5.796, 26.298],
        [109.0, 2.966, 1577.344],
        [93.0, 2.59, 18849.23],
        [72.0, 1.14, 529.69],
        [68.0, 1.87, 398.15],
        [67.0, 4.41, 5507.55],
        [59.0, 2.89, 5223.69],
        [56.0, 2.17, 155.42],
        [45.0, 0.4, 796.3],
        [36.0, 0.47, 775.52],
        [29.0, 2.65, 7.11],
        [21.0, 5.34, 0.98],
        [19.0, 1.85, 5486.78],
        [19.0, 4.97, 213.3],
        [17.0, 2.99, 6275.96],
        [16.0, 0.03, 2544.31],
        [16.0, 1.43, 2146.17],
        [15.0, 1.21, 10977.08],
        [12.0, 2.83, 1748.02],
        [12.0, 3.26, 5088.63],
        [12.0, 5.27, 1194.45],
        [12.0, 2.08, 4694.0],
        [11.0, 0.77, 553.57],
        [10.0, 1.3, 6286.6],
        [10.0, 4.24, 1349.87],
        [9.0, 2.7, 242.73],
        [9.0, 5.64, 951.72],
        [8.0, 5.3, 2352.87],
        [6.0, 2.65, 9437.76],
        [6.0, 4.67, 4690.48],
    ], 
    dtype=np.float64
)
L2 = np.array(
    [
        [52919.0, 0.0, 0.0],
        [8720.0, 1.0721, 6283.0758],
        [309.0, 0.867, 12566.152],
        [27.0, 0.05, 3.52],
        [16.0, 5.19, 26.3],
        [16.0, 3.68, 155.42],
        [10.0, 0.76, 18849.23],
        [9.0, 2.06, 77713.77],
        [7.0, 0.83, 775.52],
        [5.0, 4.66, 1577.34],
        [4.0, 1.03, 7.11],
        [4.0, 3.44, 5573.14],
        [3.0, 5.14, 796.3],
        [3.0, 6.05, 5507.55],
        [3.0, 1.19, 242.73],
        [3.0, 6.12, 529.69],
        [3.0, 0.31, 398.15],
        [3.0, 2.28, 553.57],
        [2.0, 4.38, 5223.69],
        [2.0, 3.75, 0.98],
    ], 
    dtype=np.float64
)
L3 = np.array(
    [
        [289.0, 5.844, 6283.076],
        [35.0, 0.0, 0.0],
        [17.0, 5.49, 12566.15],
        [3.0, 5.2, 155.42],
        [1.0, 4.72, 3.52],
        [1.0, 5.3, 18849.23],
        [1.0, 5.97, 242.73],
    ]
)
L4 = np.array(
    [
        [114.0, 3.142, 0.0], 
        [8.0, 4.13, 6283.08], 
        [1.0, 3.84, 12566.15]
    ], 
    dtype=np.float64
)
L5 = np.array(
    [
        [1.0, 3.14, 0.0]
    ],
    dtype=np.float64
)

# heliocentric latitude coefficients
B0 = np.array(
    [
        [280.0,     3.199,  84334.662],
        [102.0,     5.422,  5507.553],
        [80.0,      3.88,   5223.69],
        [44.0,      3.7,    2352.87],
        [32.0,      4.0,    1577.34]
    ], 
    dtype=np.float64
)
B1 = np.array(
    [
        [9.0, 3.9, 5507.55], 
        [6.0, 1.73, 5223.69]
    ], 
    dtype=np.float64
)


# heliocentric radius coefficients
R0 = np.array(
    [
        [100013989.0, 0.0, 0.0],
        [1670700.0, 3.0984635, 6283.07585],
        [13956.0, 3.05525, 12566.1517],
        [3084.0, 5.1985, 77713.7715],
        [1628.0, 1.1739, 5753.3849],
        [1576.0, 2.8469, 7860.4194],
        [925.0, 5.453, 11506.77],
        [542.0, 4.564, 3930.21],
        [472.0, 3.661, 5884.927],
        [346.0, 0.964, 5507.553],
        [329.0, 5.9, 5223.694],
        [307.0, 0.299, 5573.143],
        [243.0, 4.273, 11790.629],
        [212.0, 5.847, 1577.344],
        [186.0, 5.022, 10977.079],
        [175.0, 3.012, 18849.228],
        [110.0, 5.055, 5486.778],
        [98.0, 0.89, 6069.78],
        [86.0, 5.69, 15720.84],
        [86.0, 1.27, 161000.69],
        [65.0, 0.27, 17260.15],
        [63.0, 0.92, 529.69],
        [57.0, 2.01, 83996.85],
        [56.0, 5.24, 71430.7],
        [49.0, 3.25, 2544.31],
        [47.0, 2.58, 775.52],
        [45.0, 5.54, 9437.76],
        [43.0, 6.01, 6275.96],
        [39.0, 5.36, 4694.0],
        [38.0, 2.39, 8827.39],
        [37.0, 0.83, 19651.05],
        [37.0, 4.9, 12139.55],
        [36.0, 1.67, 12036.46],
        [35.0, 1.84, 2942.46],
        [33.0, 0.24, 7084.9],
        [32.0, 0.18, 5088.63],
        [32.0, 1.78, 398.15],
        [28.0, 1.21, 6286.6],
        [28.0, 1.9, 6279.55],
        [26.0, 4.59, 10447.39],
    ], 
    dtype=np.float64
)
R1 = np.array(
    [
        [103019.0, 1.10749, 6283.07585],
        [1721.0, 1.0644, 12566.1517],
        [702.0, 3.142, 0.0],
        [32.0, 1.02, 18849.23],
        [31.0, 2.84, 5507.55],
        [25.0, 1.32, 5223.69],
        [18.0, 1.42, 1577.34],
        [10.0, 5.91, 10977.08],
        [9.0, 1.42, 6275.96],
        [9.0, 0.27, 5486.78],
    ],
    dtype=np.float64
)
R2 = np.array(
    [
        [4359.0, 5.7846, 6283.0758],
        [124.0, 5.579, 12566.152],
        [12.0, 3.14, 0.0],
        [9.0, 3.63, 77713.77],
        [6.0, 1.87, 5573.14],
        [3.0, 5.47, 18849.23],
    ], dtype=np.float64
)
R3 = np.array([[145.0, 4.273, 6283.076], [7.0, 3.92, 12566.15]], dtype=np.float64)
R4 = np.array([[4.0, 2.56, 6283.08]], dtype=np.float64)


@cython.boundscheck(False)
@cython.wraparound(False)
cdef _term_calc(double[:,:] terms, double[:] jme):
    """
    >>> cdef double[:] input_ = np.arange(100, dtype=np.float64)
    """
    cdef int i, j, n_terms, n_jme
    cdef double A, B, C, JME
    cdef NDArray[f64, ndim=1] out
    n_terms = len(terms)
    n_jme = len(jme)
    out = np.zeros_like(jme, dtype=np.float64)
    for i in prange(n_terms, nogil=True):
        for j in range(n_jme):
            A, B, C = terms[i, 0], terms[i, 1], terms[i, 2]
            JME = jme[j]
            out[j] += A * cos(B + C * JME)
            
    return out


@cython.boundscheck(False)
@cython.wraparound(False)
cdef _earth_heliocentric_longitude_latitude_and_radius_vector(
    NDArray jme, 
):
    """
    3.2.	 Calculate the Earth heliocentric longitude, latitude, and radius vector (L, B, # and R): 
    “Heliocentric” means that the Earth position is calculated with respect to the center of the sun. 
    3.2.1. For each row of Table A4.2, calculate the term L0i (in radians), 
    L0 =	 A *cos ( B + C * JME) , (9) i i i i 
    where, 
    - i is the ith row for the term L0 in Table A4.2. 
    - Ai , Bi , and Ci are the values in the ith row and A, B, and C columns in Table 
    A4.2, for the term L0 (in radians). 
    3.2.2. Calculate the term L0 (in radians), 
    n 
    L0 = ∑ L0i ,	 (10) 
    i = 0 
    where n is the number of rows for the term L0 in Table A4.2. 
    3.2.3. Calculate the terms L1, L2, L3, L4, and L5 by using Equations 9 and 10 and 
    changing the 0 to 1, 2, 3, 4, and 5, and by using their corresponding values in"""
    # cdef NDArray L, B, R, l0, l1, l2, l3, l4, l5, b0, b1, r0, r1, r2, r3, r4
    cdef double[:] jme_view = jme
    l0 = _term_calc(L0, jme_view)
    l1 = _term_calc(L1, jme_view)
    l2 = _term_calc(L2, jme_view)
    l3 = _term_calc(L3, jme_view)
    l4 = _term_calc(L4, jme_view)
    l5 = _term_calc(L5, jme_view)

    L = np.rad2deg(
        (l0 + l1 * jme + l2 * jme**2 + l3 * jme**3 + l4 * jme**4 + l5 * jme**5) / 1e8
    )
    L %=  360

    b0 = _term_calc(B0, jme_view)
    b1 = _term_calc(B1, jme_view)
    B = np.rad2deg((b0 + b1 * jme) / 10**8)

    # - radius vector (R) in astronomical units (AU)
    r0 = _term_calc(R0, jme_view)
    r1 = _term_calc(R1, jme_view)
    r2 = _term_calc(R2, jme_view)
    r3 = _term_calc(R3, jme_view)
    r4 = _term_calc(R4, jme_view)
    

    R = (r0 + r1 * jme + r2 * jme**2 + r3 * jme**3 + r4 * jme**4) / 1e8
    
    return L, B, R

# =============================================================================
# Julian Day Conversion
# =============================================================================
@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_day(NDArray[f64, ndim=1] ut):
    cdef NDArray[f64, ndim=1] jd
    jd = ut * 1.0 / 86400 + 2440587.5
    return jd

@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_century(NDArray[f64, ndim=1] jd):
    cdef NDArray[f64, ndim=1] jc
    jc = (jd - 2451545) * 1.0 / 36525
    return jc

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_century(NDArray[f64, ndim=1] ut):
    cdef NDArray[f64, ndim=1] jd, jc
    jd = _julian_day(ut)
    jc = _julian_century(jd)
    return jc

# - ephemeris
@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_ephemeris_day(NDArray[f64, ndim=1] jd, delta_t):
    cdef NDArray[f64, ndim=1] jde
    jde = jd + delta_t * 1.0 / 86400
    return jde

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_ephemeris_day(NDArray[f64, ndim=1] ut, NDArray[f64, ndim=1] delta_t):
    cdef NDArray[f64, ndim=1] jd, jde
    jd = _julian_day(ut)
    jde = _julian_ephemeris_day(jd, delta_t)
    return jde

@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_ephemeris_century(NDArray[f64, ndim=1] jde):
    cdef NDArray[f64, ndim=1] jce
    jce = (jde - 2451545) * 1.0 / 36525
    return jce

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_ephemeris_century(NDArray[f64, ndim=1] ut, NDArray[f64, ndim=1] delta_t):
    cdef NDArray[f64, ndim=1] jd, jde, jce
    jd = _julian_day(ut)
    jde = _julian_ephemeris_day(jd, delta_t)
    jce = _julian_ephemeris_century(jde)
    return jce

@cython.boundscheck(False)
@cython.wraparound(False)
cdef _julian_ephemeris_millennium(NDArray[f64, ndim=1] jce):
    cdef NDArray[f64, ndim=1] jme
    jme = jce * 1.0 / 10
    return jme

@cython.boundscheck(False)
@cython.wraparound(False)
def julian_ephemeris_millennium(NDArray[f64, ndim=1] ut, NDArray[f64, ndim=1] delta_t):
    cdef NDArray[f64, ndim=1] jd, jde, jce, jme
    jd = _julian_day(ut)
    jde = _julian_ephemeris_day(jd, delta_t)
    jce = _julian_ephemeris_century(jde)
    jme = _julian_ephemeris_millennium(jce)
    return jme

def unix_time(x):
    cdef NDArray[f64, ndim=1] ut
    out = np.asanyarray(x, dtype="datetime64[ns]").ravel().astype(np.float64) // 1e9
    return out

import pvlib
dt = np.asanyarray(["2019-01-01 00:00:00"], dtype="datetime64[ns]")
year = dt.astype("datetime64[Y]").astype(int) + 1970
month = dt.astype("datetime64[M]").astype(int) % 12 + 1
ut = dt.astype(np.float64) // 1e9
delta_t = pvlib.spa.calculate_deltat(year, month)
ut = unix_time(dt)
jme = julian_ephemeris_millennium(ut, delta_t)

a = np.stack(_earth_heliocentric_longitude_latitude_and_radius_vector(jme))
b = np.stack([
    pvlib.spa.heliocentric_longitude(jme),
    pvlib.spa.heliocentric_latitude(jme),
    pvlib.spa.heliocentric_radius_vector(jme),
])
print(
    '\n-------\n',
    a == b,
    sep='\n'
)
import timeit
print(
    timeit.timeit(lambda: _earth_heliocentric_longitude_latitude_and_radius_vector(jme), number=1000),
    timeit.timeit(lambda: (
        pvlib.spa.heliocentric_longitude(jme),
        pvlib.spa.heliocentric_latitude(jme),
        pvlib.spa.heliocentric_radius_vector(jme),
    ), number=1000),
    
    )

[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]

-------

[[ True]
 [ True]
 [ True]]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56138002] [-3.32847347]
[98330309.81061757] [46865.54146536] [3893.90219253] [-67.56

In [336]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
import cython
from cython.parallel import prange
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np
# import cosine function
from libc.math cimport cos, sin, sqrt
cdef int i
cdef double[:,:] L0 = np.array([
    [1,2,3]
], dtype=np.float64)


@cython.boundscheck(False)
@cython.wraparound(False)
cdef main(double[:,:] terms, double[:] jme):
    """
    >>> cdef double[:] input_ = np.arange(100, dtype=np.float64)
    """


    cdef int i, j, n_terms, n_jme
    cdef double a, b, c, x
    cdef NDArray[f64, ndim=1]  output
    
    
    n_terms = len(terms)
    n_jme = len(jme)
    

    output = np.zeros_like(input_, dtype=np.float64)
    for i in prange(n_terms, nogil=True):
        for j in range(n_jme):
            a = terms[i, 0]
            b = terms[i, 1]
            c = terms[i, 2]
            x = jme[j]
            output[j] += a * cos(b + c * x)
    
    return output


cdef double[:] input_ = np.arange(100, dtype=np.float64)
    
print(main(L0, input_))

[-0.41614684  0.28366219 -0.14550003  0.0044257   0.13673722 -0.27516334
  0.40808206 -0.53283302  0.64691932 -0.74805753  0.83422336 -0.90369221
  0.95507364 -0.98733928  0.99984331 -0.99233547  0.96496603 -0.91828279
  0.85322011 -0.77108022  0.67350716 -0.56245385  0.44014302 -0.30902273
  0.17171734 -0.03097503 -0.11038724  0.24954012 -0.38369844  0.51017704
 -0.62644445  0.73017356 -0.81928825  0.89200487 -0.94686801  0.98277958
 -0.99902081  0.99526664 -0.97159219  0.92847132 -0.86676709  0.78771451
 -0.69289582  0.58420882 -0.46382887  0.33416538 -0.19781357  0.05750253
  0.08395944 -0.22374095  0.35904429 -0.48716135  0.60552787 -0.71177476
  0.80377546 -0.87968859  0.93799475 -0.97752694  0.99749392 -0.99749605
  0.97753329 -0.9380052   0.87970293 -0.80379339  0.71179593 -0.60555186
  0.48718768 -0.35907242  0.22377033 -0.08398947 -0.05747243  0.19778403
 -0.33413697  0.46380216 -0.58418435  0.69287409 -0.78769594  0.86675206
 -0.92846012  0.97158506 -0.99526371  0.99902215 -0

In [171]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
from cython.view cimport array as cvarray
cimport cython
cimport numpy as cnp
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np

cnp.import_array()

# =============================================================================
import pvlib

def test_time_conversion(date):
    dt = np.asanyarray(date, dtype="datetime64[ns]")
    year = dt.astype("datetime64[Y]").astype(int) + 1970
    month = dt.astype("datetime64[M]").astype(int) % 12 + 1
    cdef f64[:] ut = dt.astype(np.float64) // 1e9
    for i in range(len(ut)):
        ut[i] += 2
    # ut = dt.astype(np.float64) // 1e9
    # delta_t = pvlib.spa.calculate_deltat(year, month)

    # jd = pvlib.spa.julian_day(ut)
    # assert np.all(jd == julian_day(date))
    cdef NDArray[f64, ndim=1] jd = np.asarray(ut)
    return jd


for dates in [
    ["2019-01-01 00:00:00"],
    ["2019-01-01 00:00:00", "2019-01-01 00:10:00"],
    ["2019-01-01 00:00:00", "2029-02-01 00:10:00", "2019-01-01 00:20:00"],
]:
    print(test_time_conversion(dates))
    

[1.5463008e+09]
[1.5463008e+09 1.5463014e+09]
[1.5463008e+09 1.8645990e+09 1.5463020e+09]


In [157]:
%%cython
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
from cython.view cimport array as cvarray
cimport cython
cimport numpy as cnp
from numpy cimport float32_t as f32, float64_t as f64, ndarray as NDArray
import numpy as np

cnp.import_array()

ctypedef fused floating:
    f32
    f64



cdef f(
    floating[:] a,
    floating[:] b,
    floating[:] c
):
    cdef int i
    cdef int n = a.shape[0]
    cdef NDArray[floating, ndim=3] out = np.zeros((n, 3, 3), dtype=np.float64)
    for i in range(n):
        out[i, 0, 0] = a[i]
        out[i, 1, 1] = b[i]
        out[i, 2, 2] = c[i]
    
    return out


def main(
    NDArray[floating, ndim=1] a,
    NDArray[floating, ndim=1] b,
    NDArray[floating, ndim=1] c
):
    cdef NDArray[floating, ndim=3] out
    cdef floating[:] x, y, z
    x, y, z = a, b, c
    # x = a
    # y = b
    # z = c
    out = f(x, y, z)
    return out
    

    

print(main(
    np.arange(10, dtype=np.float64),
    np.arange(10, dtype=np.float64),
    np.arange(10, dtype=np.float64)

))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[2. 0. 0.]
  [0. 2. 0.]
  [0. 0. 2.]]

 [[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]]

 [[4. 0. 0.]
  [0. 4. 0.]
  [0. 0. 4.]]

 [[5. 0. 0.]
  [0. 5. 0.]
  [0. 0. 5.]]

 [[6. 0. 0.]
  [0. 6. 0.]
  [0. 0. 6.]]

 [[7. 0. 0.]
  [0. 7. 0.]
  [0. 0. 7.]]

 [[8. 0. 0.]
  [0. 8. 0.]
  [0. 0. 8.]]

 [[9. 0. 0.]
  [0. 9. 0.]
  [0. 0. 9.]]]


In [140]:
%%cython
from cython.view cimport array as cvarray
import numpy as np

# Memoryview on a NumPy array
narr = np.arange(27, dtype=np.dtype("i")).reshape((3, 3, 3))
cdef int [:, :, :] narr_view = narr

# Memoryview on a C array
cdef int[3][3][3] carr
cdef int [:, :, :] carr_view = carr

# Memoryview on a Cython array
cyarr = cvarray(shape=(3, 3, 3), itemsize=sizeof(int), format="i")
cdef int [:, :, :] cyarr_view = cyarr

# Show the sum of all the arrays before altering it
print("NumPy sum of the NumPy array before assignments: %s" % narr.sum())

# We can copy the values from one memoryview into another using a single
# statement, by either indexing with ... or (NumPy-style) with a colon.
carr_view[...] = narr_view
cyarr_view[:] = narr_view
# NumPy-style syntax for assigning a single value to all elements.
narr_view[:, :, :] = 3

# Just to distinguish the arrays
carr_view[0, 0, 0] = 100
cyarr_view[0, 0, 0] = 1000

# Assigning into the memoryview on the NumPy array alters the latter
print("NumPy sum of NumPy array after assignments: %s" % narr.sum())

# A function using a memoryview does not usually need the GIL
cdef int sum3d(int[:, :, :] arr) nogil:
    cdef size_t i, j, k, I, J, K
    cdef int total = 0
    I = arr.shape[0]
    J = arr.shape[1]
    K = arr.shape[2]
    for i in range(I):
        for j in range(J):
            for k in range(K):
                total += arr[i, j, k]
    return total








# A function accepting a memoryview knows how to use a NumPy array,
# a C array, a Cython array...
print("Memoryview sum of NumPy array is %s" % sum3d(narr))
print("Memoryview sum of C array is %s" % sum3d(carr))
print("Memoryview sum of Cython array is %s" % sum3d(cyarr))
# ... and of course, a memoryview.
print("Memoryview sum of C memoryview is %s" % sum3d(carr_view))

NumPy sum of the NumPy array before assignments: 351
NumPy sum of NumPy array after assignments: 81
Memoryview sum of NumPy array is 81
Memoryview sum of C array is 451
Memoryview sum of Cython array is 1351
Memoryview sum of C memoryview is 451


In [9]:
# import pvlib

UNIX_TIME_ZERO = np.datetime64('1970-01-01T00:00:00')

dates = np.array(["2019-01-01 00:00:00", "2019-01-01 00:10:00"], dtype="datetime64[ns]")
# unixtime = (dates - np.datetime64('1970-01-01T00:00:00')) / np.timedelta64(1, 's')
# unixtime == dates.astype(np.float64) // 1e9

def to_unix_time(x) -> np.ndarray:
    return np.asanyarray(x, dtype="datetime64[ns]").astype(np.float64) // 1e9

np.all(
    (
        dates.astype(np.float64) // 1e9 == (dates - np.datetime64('1970-01-01T00:00:00')) / np.timedelta64(1, 's')
    ) 
    & (
        dates.astype(np.float64) // 1e9 == to_unix_time(dates)
    
    )
    & (
        to_unix_time(dates) == to_unix_time(["2019-01-01 00:00:00", "2019-01-01 00:10:00"])
    )
)



True

AttributeError: 'tuple' object has no attribute 'shape'